version: "3.9"
services:
  app:
    container_name: app-googleMap
    build: ./infra/php
    volumes:
      - ./src:/data

  web:
    container_name: web-googleMap
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    container_name: db-googleMap
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3308:3306

volumes:
  db-store: